show-failed-logs: True
keep-going: True
keep-incomplete: True
rerun-incomplete: True
printshellcmds: False

default-remote-provider: "GS"
default-remote-prefix: "orcestradata/CCLE-Pharmacoset_Snakemake"
# default-storage-provider: "gcs"
# default-storage-prefix: "gs://orcestradata/CCLE-Pharmacoset_Snakemake"
# storage-gcs-keep-local: True

# When running on Kubernetes
jobs: 256